server:
  port: 8011
#debug: true
spring:
  boot:
    admin:
      client:
        url: http://localhost:8016
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: mall-user
  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
