server:
  port: 8013
#debug: true
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: mall-user
  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
