server:
  port: 8019

spring:
  application:
    name: mall-gateway
  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    consul:
      host: localhost
      port: 8500
  #本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
  #rabbitmq:
    #host: 127.0.0.1
    #port: 15672
    #username: guest
    #password: guest
